### Suggest claims

POST https://{{sse-api-host}}/v1/suggest-claims HTTP/1.1
content-type: application/json

{}

### Validate a claim

POST https://{{sse-api-host}}/v1/validate-claim HTTP/1.1
content-type: application/json

{
  "claim": "Some citizens who can currently vote should not be able to."
}

### Create a new session

POST https://{{sse-api-host}}/v1/sessions HTTP/1.1
content-type: application/json

{
  "claim": "Feelings are more important than truth.",
  "confidence": "strongly disagree"
}

### Retrieve a session

GET https://{{sse-api-host}}/v1/sessions/8675309 HTTP/1.1

### Send an "start chat" message

POST https://{{sse-api-host}}/v1/sessions/8675309/start-chat HTTP/1.1
content-type: application/json

{
  "content": "I strongly disagree with the claim: Feelings are more important than truth."
}

### Send a "guess reasons" message

POST https://{{sse-api-host}}/v1/sessions/8675309/guess-reasons HTTP/1.1
content-type: application/json

{
  "content": "I strongly disagree with the claim: Feelings are more important than truth."
}

### Send a "probe confidence" message

POST https://{{sse-api-host}}/v1/sessions/8675309/probe-confidence HTTP/1.1
content-type: application/json

{
  "content": "I strongly disagree with the claim: Feelings are more important than truth."
}

### Send a "probe reasons" message

POST https://{{sse-api-host}}/v1/sessions/8675309/probe-reasons HTTP/1.1
content-type: application/json

{
  "content": "I strongly disagree with the claim: Feelings are more important than truth."
}

### Send an "end chat" message

POST https://{{sse-api-host}}/v1/sessions/8675309/end-chat HTTP/1.1
content-type: application/json

{
  "content": "I strongly disagree with the claim: Feelings are more important than truth."
}

###
