###

POST https://{{sse-api-host}}/v1/suggest-claims HTTP/1.1
content-type: application/json

{}

###

POST https://{{sse-api-host}}/v1/validate-claim HTTP/1.1
content-type: application/json

{
  "claim": "Some citizens who can currently vote should not be able to."
}

###

POST https://{{sse-api-host}}/v1/sessions HTTP/1.1
content-type: application/json

{
  "claim": "Feelings are more important than truth.",
  "confidence": "strongly disagree"
}

###

GET https://{{sse-api-host}}/v1/sessions/8675309 HTTP/1.1

###

POST https://{{sse-api-host}}/v1/sessions/8675309/guess-reasons HTTP/1.1
content-type: application/json

{
  "content": "I strongly disagree with the claim: Feelings are more important than truth.",
  "newConversation": true
}

###

POST https://{{sse-api-host}}/v1/sessions/8675309/probe-confidence HTTP/1.1
content-type: application/json

{
  "content": "I strongly disagree with the claim: Feelings are more important than truth.",
  "newConversation": true
}

###

POST https://{{sse-api-host}}/v1/sessions/8675309/probe-reasons HTTP/1.1
content-type: application/json

{
  "content": "I strongly disagree with the claim: Feelings are more important than truth.",
  "newConversation": true
}

###
